services:
  client:
    build:
      context: .
    stdin_open: true
    tty: true
    network_mode: "host"
    command:
      [
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
      ]